spring.application.name=TrekRent
spring.profiles.active=dev

spring.datasource.url=jdbc:postgresql://pwr.mnowacki.cloud:5432/trekrentdb
spring.datasource.username=trekrent
spring.datasource.password=trekrent
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# W??czenie JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true 